# Generated by Django 5.0.3 on 2024-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('posted_date', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
            ],
        ),
    ]
