# Generated by Django 5.0.3 on 2024-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
