# Generated by Django 5.0.3 on 2024-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reply',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
