# Generated by Django 5.0.3 on 2024-11-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notifications_book_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photot',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
