# Generated by Django 5.0.3 on 2024-11-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_register_photot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='photot',
            new_name='photo',
        ),
    ]
