# Generated by Django 5.0.3 on 2024-11-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_photot_register_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='book_ticket',
            new_name='available_ticket',
        ),
    ]
